### ISSUE TITLE
Bug if no ingredients

### ISSUE THREAD

**Issue by Bart-dh** [AbstractiveOdooPartner/vh-demo#6]
@dinuth-perera this causes error if there are no ingredients, probably also if there are no ingredients without category. https://github.com/AbstractiveOdooPartner/vh-demo/blob/3ab89481511a6816f973703f6bcc1bf60a26dcf0/mrp_labeling/models/product.py#L326

**Comment by dinuth-perera** [comment]
fixed : now only calling this function ,if there base level ingredients
https://github.com/AbstractiveOdooPartner/vh-demo/commit/b3e0caa28c89672e77d6a7ff3ff9b85df64f4e33

**Comment by Bart-dh** [comment]
Did you test the case where all ingredients have a category?
